const data = {
    status: "success",
    items: [
      {
        id: 1,
        name: "Aparador",
        text: "Aparador 2 puertas xd",
        price: 300,
        photo: require('./imagenes/aparadorA.jpg'),
        title1: "Gonzalo Diaz",
        description1: "Un capo AAAA",
        title2: "Añadido al carrito",
        description2:"Confirmado",
      },
      {
        id: 2,
        name: "Nike",
        text: 401,
        price: 400,
        photo: require('./imagenes/aparadorB.jpg'),
        title1: "Octavio Martin",
        description1: "Un capo AAAA",
        title2: "Añadido al carrito",
        description2:"Confirmado",
      },
      {
        id: 3,
        name: "Nike",
        text: 401,
        price: 450,
        photo: require('./imagenes/aparadorC.jpg'),
        title1: "Italo Belloti",
        description1: "Un capo AAAA",
        title2: "Añadido al carrito",
        description2:"Confirmado",
      },
      {
        id: 4,
        name: "Nike",
        text: 401,
        price: 100,
        photo: require('./imagenes/sillonA.jpg'),
        title1: "Joaquin Aguero",
        description1: "Un capo AAAA",
        title2: "Añadido al carrito",
        description2:"Confirmado",
      },
      {
        id: 5,
        name: "Nike",
        text: 401,
        price: 700,
        photo: require('./imagenes/sillonB.jpg'),
        title1: "Augusto Aguilar",
        description1: "Un capo AAAA",
        title2: "Añadido al carrito",
        description2:"Confirmado",
      },
      {
        id: 6,
        name: "Nike",
        text: 401,
        price: 900,
        photo: require('./imagenes/sillonC.jpg'),
        title1: "Matias Castro",
        description1: "Un capo AAAA",
        title2: "Añadido al carrito",
        description2:"Confirmado",
      },
    ],
  };
  
  export default data;